# Generated by Django 5.1.4 on 2025-01-09 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=30)),
                ('t1run1', models.IntegerField(default=0)),
                ('t1run2', models.IntegerField(default=0)),
                ('t2run1', models.IntegerField(default=0)),
                ('t2run2', models.IntegerField(default=0)),
                ('t1wkt1', models.IntegerField(default=0)),
                ('t1wkt2', models.IntegerField(default=0)),
                ('t2wkt1', models.IntegerField(default=0)),
                ('t2wkt2', models.IntegerField(default=0)),
                ('t1overs1', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('t1overs2', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('t2overs1', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('t2overs2', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_matches', to=settings.AUTH_USER_MODEL)),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_striker_matches', to=settings.AUTH_USER_MODEL)),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='striker_matches', to=settings.AUTH_USER_MODEL)),
                ('batting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_matches', to='scorecard.team')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='scorecard.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='scorecard.team')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs1', models.IntegerField(default=0)),
                ('runs2', models.IntegerField(default=0)),
                ('balls1', models.IntegerField(default=0)),
                ('balls2', models.IntegerField(default=0)),
                ('overs1', models.IntegerField(default=0)),
                ('overs2', models.IntegerField(default=0)),
                ('wkt1', models.IntegerField(default=0)),
                ('wkt2', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='scorecard.match')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='scorecard.team')),
            ],
        ),
    ]
