# Generated by Django 5.1.4 on 2025-01-11 07:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_alter_match_batting_alter_match_bowler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='innings',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='match',
            name='won',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won', to='scorecard.team'),
        ),
    ]
