# Generated by Django 5.1.4 on 2025-01-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_match_innings_match_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='out1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='players',
            name='out2',
            field=models.BooleanField(default=False),
        ),
    ]
