# Generated by Django 5.1.4 on 2025-01-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0004_players_out1_players_out2'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='played',
            field=models.IntegerField(default=0),
        ),
    ]
