# Generated by Django 5.1.4 on 2025-01-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0005_team_matches_won_team_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='bruns1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='bruns2',
            field=models.IntegerField(default=0),
        ),
    ]
