# Generated by Django 5.1.4 on 2025-01-14 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0007_alter_players_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
