# Generated by Django 5.1.4 on 2025-01-25 14:11

import datetime
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0008_match_created_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('match_id', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('t1run1', models.IntegerField(default=0)),
                ('t1run2', models.IntegerField(default=0)),
                ('t2run1', models.IntegerField(default=0)),
                ('t2run2', models.IntegerField(default=0)),
                ('t1wkt1', models.IntegerField(default=0)),
                ('t1wkt2', models.IntegerField(default=0)),
                ('t2wkt1', models.IntegerField(default=0)),
                ('t2wkt2', models.IntegerField(default=0)),
                ('t1overs1', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('t1overs2', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('t2overs1', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('t2overs2', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('innings', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('batting', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scorecard.team')),
                ('bowler', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('non_striker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('striker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scorecard.team')),
                ('team2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scorecard.team')),
                ('won', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scorecard.team')),
            ],
            options={
                'verbose_name': 'historical match',
                'verbose_name_plural': 'historical matchs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPlayers',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('runs1', models.IntegerField(default=0)),
                ('runs2', models.IntegerField(default=0)),
                ('balls1', models.IntegerField(default=0)),
                ('balls2', models.IntegerField(default=0)),
                ('overs1', models.IntegerField(default=0)),
                ('overs2', models.IntegerField(default=0)),
                ('wkt1', models.IntegerField(default=0)),
                ('wkt2', models.IntegerField(default=0)),
                ('bruns1', models.IntegerField(default=0)),
                ('bruns2', models.IntegerField(default=0)),
                ('out1', models.BooleanField(default=False)),
                ('out2', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scorecard.match')),
                ('name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scorecard.team')),
            ],
            options={
                'verbose_name': 'historical players',
                'verbose_name_plural': 'historical playerss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
