# Generated by Django 5.1.4 on 2025-01-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0009_historicalmatch_historicalplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatch',
            name='ball_record',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='ball_record',
            field=models.JSONField(default=list),
        ),
    ]
