# Generated by Django 4.2.21 on 2025-05-31 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scorecard', '0010_historicalmatch_ball_record_match_ball_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayers',
            name='catches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalplayers',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalplayers',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='catches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Wicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowled_wickets', to=settings.AUTH_USER_MODEL)),
                ('caught_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caught_wickets', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wickets', to='scorecard.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wickets', to='scorecard.players')),
                ('run_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_out_wickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bowler', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('caught_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scorecard.match')),
                ('player', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scorecard.players')),
                ('run_out_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical wicket',
                'verbose_name_plural': 'historical wickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
