# Generated by Django 4.2.21 on 2025-05-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0011_historicalplayers_catches_historicalplayers_fours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplayers',
            name='catches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='catches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
