# Generated by Django 4.2.21 on 2025-05-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0012_alter_historicalplayers_catches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplayers',
            name='fours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplayers',
            name='sixes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='fours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='sixes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
